### ISSUE TITLE
Poetry Add fails on Psycopg2 dependency

### ISSUE THREAD

**Issue by leo-jp-edwards** [turbulette/turbulette#141]
**Describe the bug**
On running `poetry add turbulette` as described in the readme the command errors on trying to install `psycopg2` from the pyproject.toml dependency tree.

**To Reproduce**
Run `poetry add turbulette`

**Expected behavior**
The command would ideally run to add turbulette to pyproject.toml

**Screenshots**

**Environment**

If possible, a full reproducible environment (ex: a Dockerfile)

* [ ] **Explain with a simple sentence the expected behavior**
* [ ] **Turbulette version:** _e.g 0.1.0_
* [ ] **Python version:** _e.g 3.6_
* [ ] **Executed in docker:** _Yes|No_
* [ ] **Dockerfile sample:** _Link of sample_
* [ ] **GraphQL Schema & Query:** _e.g gist, pastebin or directly the query_
* [ ] **Is it a regression from a previous versions?** _e.g Yes|No_
* [ ] **Stack trace**

**Additional context**

**Comment by leo-jp-edwards** [comment]
I am opening a bug report but happy to implement a fairly easy fix for this if needed? I believe it should be as simple as changing the pyproject.toml dependency on psycopg2 to be psycopg2-binary.

**Comment by gazorby** [comment]
Hi @leo-jp-edwards , 

psychopg2 needs to be built from source when installed from PyPI, did you install the [required build dependencies](https://www.psycopg.org/docs/install.html#build-prerequisites) ?

psychopg2-binary comes with its own C librairies and is only meant to be used by beginners to start playing with python and postgres, not for production use. However we could add an `express` dependency group that would use binary version of packages that need to be built from source.

**Comment by leo-jp-edwards** [comment]
My apologies - my experience has been with [asyncpg](https://github.com/MagicStack/asyncpg) so I thought it was a bug :)
