### ISSUE TITLE
support for different database systems sql / nosql - (orm / odm) 

### ISSUE THREAD

**Issue by Barceloch** [turbulette/turbulette#52]
I'm trying migrate it to use with mongo

**Comment by gazorby** [comment]
Hey @Barceloch 

Sorry I didn't had the time to think about it, I'm busy with the docs. Are you still interested in this feature?

**Comment by Barceloch** [comment]
> Hey @Barceloch
> 
> Sorry I didn't had the time to think about it, I'm busy with the docs. Are you still interested in this feature?

I understand!, :) no problem, yes I'm still interested... 
I'm trying to understand more about python and reading the turbulete code, I'm really interested in being able to use it and even contribute to its development ...
